version: '3.1'
services:
  meilipanel:
    build: ./meilipanel
    ports:
     - "9090:80"
    depends_on:
     - meilisocket
    network_mode: host
  meilisocket:
    build: ./meilisocket
    ports:
     - "9191:9191"
    network_mode: host
  
